### ISSUE TITLE
University and College Data | update Footer

### ISSUE THREAD

**Issue by tu-chill** [TULiberalArts/TUtheme#10]
The Template seems to be printing out more data than we need. A commit to the config.yml changed the structure of the data.

![screen shot 2017-02-15 at 8 36 48 am](https://cloud.githubusercontent.com/assets/12816361/22976717/f7d8a306-f359-11e6-97d1-fa458cbf6588.png)

**Comment by tu-chill** [comment]
I'm getting on an airplane. I'll be back on the 22nd. This looks like the last Show Stopper before going live.

**Comment by lidopaglia** [comment]
my fault. This has already been fixed in the theme footer. I'll push to all sites to trigger the new build.
