### ISSUE TITLE
Mega menu | Homepage link

### ISSUE THREAD

**Issue by tu-chill** [TULiberalArts/TUtheme#13]
make the text "College of Liberal Arts" link to "liberalarts.temple.edu" remove text CLA Homepage. 

<img width="1101" alt="screen shot 2017-02-24 at 4 48 26 pm" src="https://cloud.githubusercontent.com/assets/12816361/23322288/36537594-fab1-11e6-856e-06d04deae145.png">

Never use CLA and never use the word homepage.

**Comment by tu-chill** [comment]
footer links seem to suffer the same fate as Temple University. 

![screen shot 2017-02-27 at 2 34 59 pm](https://cloud.githubusercontent.com/assets/12816361/23376419/01303744-fcfa-11e6-97f0-cfa34dcd1f05.png)

**Comment by pixelyunicorn** [comment]
Fixed in  e310f3a
