### ISSUE TITLE
no 404.html

### ISSUE THREAD

**Issue by lidopaglia** [TULiberalArts/TUtheme#2]
S3 sites are configured to look for and serve an error document 404.html which does not exist in the theme yet.

**Comment by pixelyunicorn** [comment]
It looks like Jekyll themes does not (yet) allow for universal 404 errors, so I'll just make a 404.html for each repo and push it

**Comment by lidopaglia** [comment]
sounds good.

**Comment by pixelyunicorn** [comment]
The S3 bucket does not seem to like rendering 404s. http://develop.cla.temple.edu/global-studies/404.html works but http://develop.cla.temple.edu/global-studies/fadsghjfhklfxz/ does not.

Does some kind of page rule need to be created?

**Comment by lidopaglia** [comment]
the path to the 404.html document on s3 was not correctly defined. Fixed now for global-studies. I will update it now for all remaining sites.
