### ISSUE TITLE
Please add a Contact Us Navigation Yaml file for "Contact Us" tab

### ISSUE THREAD

**Issue by CVE82** [TULiberalArts/TUtheme#20]
Victor can you please add a Contact Us yaml file so I can enter the contact information for each program:
- Department Chair
- Undergraduate Chair
- Graduate Chair 
- Department Administrator
- Undergraduate Coordinator (if they have one)
- Graduate Coordinator (if they have one)
** I will remove the unnecessary fields as I go through and tailor each program**

This will be a new navigation tab, Chris and I talked about this before and forgot to add it in the master branch. Thank you!

**Comment by tu-chill** [comment]
we are going to remove contact us from tabs
