### ISSUE TITLE
Resource Page | Design for Program Contacts

### ISSUE THREAD

**Issue by tu-chill** [TULiberalArts/TUtheme#22]
We've eliminated the "contact us" tab and moved contact information onto the "Resources" tab. This page is intended for prospective students, current students, faculty, and staff. The list should be obvious and easily scanned.

![screen shot 2017-03-08 at 6 07 02 am](https://cloud.githubusercontent.com/assets/12816361/23701809/5800c214-03c6-11e7-98ed-839eb5d29048.png)

**Comment by tu-chill** [comment]
we talked about this and thought we had a solution.

**Comment by tu-chill** [comment]
@ZMcGroarty did we document what we wanted somewhere? if so, where? and can you link it here?

**Comment by ZMcGroarty** [comment]
No, we only discussed whether it was necessary to have most of these contacts listed. (Cherry&White internal vs marketing site external). 

In a pinch all I might do is decrease line heights and bold Chair titles.

**Comment by tu-chill** [comment]
<img width="1528" alt="screen shot 2017-04-05 at 12 46 00 pm" src="https://cloud.githubusercontent.com/assets/12816361/24716830/41e2ea22-19fe-11e7-8430-3a689a94e901.png">
@ZMcGroarty looks like on some pages formatting has been added. I'm going to close this ticket and put in an issue that better address the need for contact info to be available where and when users will need it rather than phonebook page. #letyourfingersdothewalking

![yellowbook](https://cloud.githubusercontent.com/assets/12816361/24716994/e536579a-19fe-11e7-8e35-98df6fba23d0.jpg)
