### ISSUE TITLE
Travis | very angry with us

### ISSUE THREAD

**Issue by tu-chill** [TULiberalArts/TUtheme#23]
@LabLayers I know you are currently working on this. Just wanted to get it into the issues. Travis is failing to build. Other repositories can reference this issue for issues that are caused by this issue.

**Comment by pixelyunicorn** [comment]
I am working on it, right now it seems to fail when it's pulling feeds that aren't currently in drupal

**Comment by pixelyunicorn** [comment]
Fixed

**Comment by tu-chill** [comment]
I'll make sure feeds are at the correct URL tonight. The URL you are expecting is defined in config?
