### ISSUE TITLE
TODO: Move card grid to flexbox

### ISSUE THREAD

**Issue by pixelyunicorn** [TULiberalArts/TUtheme#25]
Moving cards to flexbox will fix issues with cards being unevenly or oddly sized.

![image](https://cloud.githubusercontent.com/assets/607807/24256001/6a380a20-0fbd-11e7-8b54-947daa74b524.png)

**Comment by tu-chill** [comment]
@LabLayers we don't need flexbox. Materialize has this covered?

**Comment by tu-chill** [comment]
![makeitso](https://cloud.githubusercontent.com/assets/12816361/24712461/ecd567f6-19f0-11e7-87eb-2185a6201f9c.jpg)
