### ISSUE TITLE
jewish studies link incorrect in college nav

### ISSUE THREAD

**Issue by lidopaglia** [TULiberalArts/TUtheme#27]
fyi...

requests to https://liberalarts.temple.edu/academics/jewish-studies are being redirected to https://www.cla.temple.edu/asian-studies/

https://liberalarts.temple.edu/academics/jewish-studies is linked in the college nav.

**Comment by CVE82** [comment]
Quick question, why is jewish-studies re-directing to asian-studies?

**Comment by tu-chill** [comment]
cut out the redirect from the menu - now to find the culprit in drupal

**Comment by CVE82** [comment]
sweet!

**Comment by lidopaglia** [comment]
i changed the nav link to /jewishstudies in https://github.com/TULiberalArts/TUtheme/commit/9b1a65bd811618f72423ad2baeb39e1dac3a72b0 since /jewish-studies currently results in a 404 and htmlproofer was breaking builds as a result.
