### ISSUE TITLE
SEO enhancement | Meta

### ISSUE THREAD

**Issue by tu-chill** [TULiberalArts/TUtheme#28]
We are getting dinged for having the same meta description on pages. Front-Matter or a data file to hold meta for each page.

We know that keywords alone do not help SEO, but they can add weight to descriptions and sitemaps. For this, we could include the site keywords (2 or 3) and then append page keywords with front-matter or data file.

**Comment by CVE82** [comment]
I am in the process of finishing the remainder of the programs in readable.io to attain keywords. I will complete this by next week.
