### ISSUE TITLE
person-links ul class pushing content outside div on mobile

### ISSUE THREAD

**Issue by lidopaglia** [TULiberalArts/TUtheme#3]
faculty bio urls (person-links ul class) are pushing outside the gray background on mobile.

**Comment by tu-chill** [comment]
![screen shot 2017-01-18 at 12 42 47 am](https://cloud.githubusercontent.com/assets/12816361/22052237/17ad127e-dd17-11e6-8a39-8c5cde312dfb.png)

**Comment by tu-chill** [comment]
I closed the wrong issue. duh
