### ISSUE TITLE
Faculty Page | Add multiple lists

### ISSUE THREAD

**Issue by tu-chill** [TULiberalArts/TUtheme#30]
Example:

Global Studies has asked to display Faculty and Steering Committee lists. Global Studies may be a long tail example. the program doesn't have its own department or faculty but is made up of a great number of faculty who teach in other programs.

**Comment by CVE82** [comment]
@tu-chill what are we going to do about this list? There will be other programs with this issue..

**Comment by tu-chill** [comment]
We have a version of a solution for this in philosophy and neuroscience. The solution is not scalable. We add a local layout, and after the source data file is parsed, we include an HTML file.

**Comment by tu-chill** [comment]
No longer adding a local layout. but using the page frontmatter and logic variables to include files
