### ISSUE TITLE
should content move under faculty images on mobile?

### ISSUE THREAD

**Issue by lidopaglia** [TULiberalArts/TUtheme#4]
seems like lots of whitespace could be filled with content to make things easier to read.

**Comment by tu-chill** [comment]
yes. I think we can tighten up the mobile experience
![screen shot 2017-01-18 at 12 44 38 am](https://cloud.githubusercontent.com/assets/12816361/22052303/65a5eece-dd17-11e6-8535-7d7fe050ea10.png)

**Comment by pixelyunicorn** [comment]
Fixed in e959bd0
