### ISSUE TITLE
Program News- Expose Intro Paragraph on Landing Page

### ISSUE THREAD

**Issue by CVE82** [TULiberalArts/TUtheme#45]
Hey WC, I went into the landing page views, landing page content type and individual landing page settings and I cannot figure out how to expose the intro paragraphs I have added from Nick. They are in the body field of the program landing page. Thanks! The 3 we have so far are:

- AAAS
- American Studies
- Anthropology

**Comment by tu-chill** [comment]
these are exposed. will need to look at css.
