### ISSUE TITLE
The main navigation drop down menus are not working 

### ISSUE THREAD

**Issue by CVE82** [TULiberalArts/TUtheme#49]
The main navigation drop down menu to get to the programs is not working across multiple sites.

I removed the image since our repos are public and didn't know if emails were private.

**Comment by tu-chill** [comment]
New nav and old nav were having a war. No one wins. Everyone loses. The bug is squashed, but all program, center, and admin repos need to be rebuilt.

**Comment by CVE82** [comment]
@tu-chill I have restarted the theme and all sites and some are still not working. I can compose a list of those that are still not working... ?

**Comment by tu-chill** [comment]
lolz, I left the wrong comment. 

So this is fixed. There was a namespacing issue with one of the materialize methods and a method that we use to call the action.

**Comment by CVE82** [comment]
@tu-chill is this closeout message supposed to be for the faculty issues somewhere in another repo?
