### ISSUE TITLE
tla-header | nav links with multiple words are being cut off

### ISSUE THREAD

**Issue by tu-chill** [TULiberalArts/TUtheme#58]
Next Stops is only Next. This is not for all just for pages long texts or lots of links or both. it looks like there is a padding and display block we should look at

**Comment by CVE82** [comment]
@tu-chill we need to add some padding back in, the titles are cutting off again. 
![image](https://user-images.githubusercontent.com/15130721/50928111-b9808b00-1427-11e9-83e4-099a3ebb7496.png)
