### ISSUE TITLE
news and Events widget for program pages

### ISSUE THREAD

**Issue by tu-chill** [TULiberalArts/TUtheme#7]
global studies pages are where this was first identified.
https://github.com/TULiberalArts/Global-Studies/issues/19

Drupal will provide JSON feed. 

- The first widget should list the last 4 or 5. 

- If there is only one, we can switch view it as a card.

- if there are no news or media mentions, we'll need some evergreen content to link to our press room.

**Comment by tu-chill** [comment]
@zepstein we'll need the evergreen language for the No New and No Events blocks

**Comment by tu-chill** [comment]
https://github.com/TULiberalArts/Global-Studies/issues/19 has images of the blocks. This issue was discovered and first created in the global studies project

**Comment by tu-chill** [comment]
![252d6a70-f90a-11e6-8594-28bcf8874a87](https://cloud.githubusercontent.com/assets/12816361/23771263/5851215e-04e4-11e7-8096-38bab81f547f.jpg)
![20fea98c-f90a-11e6-8d7e-b5ce166997a7](https://cloud.githubusercontent.com/assets/12816361/23771264/5851d1b2-04e4-11e7-8a69-29cb1466ed22.jpg)
![d873ff0e-f90a-11e6-9087-49ba024d05d9](https://cloud.githubusercontent.com/assets/12816361/23771265/585406a8-04e4-11e7-93f6-08e360153022.jpg)
![c205fefa-ff56-11e6-9289-1029f48f6d0e](https://cloud.githubusercontent.com/assets/12816361/23771266/5854be5e-04e4-11e7-95ac-b11109a28704.png)

**Comment by pixelyunicorn** [comment]
What should the placeholder text for news and events say?

**Comment by tu-chill** [comment]
Zach we need words.

C.Hill
Marketing Technology
College of Liberal Arts
Temple University

On Mar 16, 2017, at 4:04 PM, Victor Lourng <notifications@github.com<mailto:notifications@github.com>> wrote:


What should the placeholder text for news and events say?

-

**Comment by zepstein** [comment]
How's this?

**Events**
From lectures, to film screenings, to networking opportunities with some of the region's biggest employers, events at the College of Liberal Arts are designed to support your life's work. [View Events]

**News**
We are daring, ambitious, creative thinkers. Simultaneously civic-minded and globally conscious, our students and faculty are engaged in the community and care about our world. [Read Our Stories]

**Comment by tu-chill** [comment]
@zepstein Words work for me. 
@ZMcGroarty white text on black is still the look we want to start?
@LabLayers we can send that text if there are no results in drupal. But if we are already adding logic on the Jekyll build side to accommodate the style and change of text in the link, I'd rather the logic in one place on the Jekyll build side. Maybe instead of passing nothing or "[ ] which is what I think Drupal currently passes, Drupal can send a boolean.

**Comment by pixelyunicorn** [comment]
This can be done in Jekyll

**Comment by tu-chill** [comment]
aye


On Mar 17, 2017, at 4:37 PM, Victor Lourng <notifications@github.com<mailto:notifications@github.com>> wrote:


This can be done in Jekyll
