### ISSUE TITLE
Temple University nav element not functional

### ISSUE THREAD

**Issue by lidopaglia** [TULiberalArts/TUtheme#8]
Temple logo doesn't link to anything. Also, text becomes blurry as the logo seems to get duplicated and overlaid on top of itself when clicked.

![tutheme-temple-nav](https://cloud.githubusercontent.com/assets/1696777/22945632/dc8191fe-f2c2-11e6-9f05-f72ac9636566.gif)

**Comment by pixelyunicorn** [comment]
Can't seem to reproduce this from my end, what browser/version/os are you using?

**Comment by lidopaglia** [comment]
visiting https://develop.cla.temple.edu/global-studies/ on macOS 10.12.2

happens for me with Chrome 56.0.2924.87 (64-bit) and Safari 10.0.2. 

Safari results in the text overlay seen above.

**Comment by pixelyunicorn** [comment]
That's bizarre, doesn't seem to happen from my end from Safari 10.0.3 (12602.4.3) and Mac 10.12.3 Beta (16D17a) or the new iMac

**Comment by lidopaglia** [comment]
when you visit https://develop.cla.temple.edu/global-studies/ and click on the temple university logo it links you to something?

**Comment by pixelyunicorn** [comment]
Oh, that's supposed to link to Temple's homepage. I'll fix that in my next push

**Comment by pixelyunicorn** [comment]
But I can't seem to replicate the text overlay effect

**Comment by lidopaglia** [comment]
Text overlay only happens for me in Safari.

**Comment by lidopaglia** [comment]
Looks like updating the `_config.yml` with 80ddc10f640381ba02052de34a0c89933ad45534 for `site.university.url` fixed the link generation issue and is now working in the footer. 

However, even though the link in the university logo nav at top is now correctly generated, clicking on the link still does not  load the target url in either Safari or Chrome for me. I also tried 51.0.1 (32-bit) of Firefox on Windows which results in the same behavior.

**Comment by pixelyunicorn** [comment]
This issue has since been fixed, does the link work for you now @lidopaglia?

**Comment by lidopaglia** [comment]
yes. working now across browsers. thanks.
