### ISSUE TITLE
Program nav on mobile links to anchor

### ISSUE THREAD

**Issue by lidopaglia** [TULiberalArts/TUtheme#9]
On mobile clicking on the collapsed program menu results in jumping down to the menu anchor resulting in the top nav disappearing from view. Also, the hamburger menu glyph has a trailing underscore char ( '_' ) link.

Thoughts on moving the program nav to a new row on mobile to give more room to the program title and not have it jump down when the menu is activated?

![tutheme-program-nav](https://cloud.githubusercontent.com/assets/1696777/22945971/0f4f8b80-f2c4-11e6-8001-4afe59f89216.gif)

**Comment by tu-chill** [comment]
I agree we need to do something with our mobile header. Things still seem jumbled.
